---
name: build
'on':
  pull_request:
  push:
    branches:
      - '**'
  schedule:
    - cron: "14 09 01 * *"

defaults:
  run:
    working-directory: 'webarchitect609.jet_brains_toolbox'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: 'webarchitect609.jet_brains_toolbox'

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install yamllint ansible ansible-lint

      - name: Lint code
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: ubuntu2204
            playbook: converge.yml
          - distro: ubuntu2004
            playbook: converge.yml
          - distro: ubuntu1804
            playbook: converge.yml

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: 'webarchitect609.jet_brains_toolbox'

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
